version: '3'

networks:
  backend:
    external: true
    
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    networks:
      - backend
  
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks:
      - backend