# Development Stack

version: '3'

networks:
  backend:


services:
  web:
    user: 1000:1000
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/code
      - /etc/passwd:/etc/passwd:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8888:8888"
    networks:
      - backend
