# Generated by Django 4.1 on 2022-10-03 14:30

import api.helper
import api.models.fields.Fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1024)),
                ('street2', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zipCode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('country', models.CharField(default='us', max_length=2)),
                ('county', models.CharField(max_length=128)),
                ('latitude', models.FloatField(null=True)),
                ('longitute', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionKey', api.models.fields.Fields.RegionField(max_length=2)),
                ('sequenceKey', models.DecimalField(decimal_places=0, max_digits=6)),
                ('addendumKey', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gateCode', models.CharField(max_length=15)),
                ('openSite', models.BooleanField()),
                ('requesterName', models.CharField(max_length=60)),
                ('ownerName', models.CharField(max_length=60)),
                ('poNumber', models.CharField(max_length=10)),
                ('excludeTax', models.BooleanField()),
                ('laborHours', models.IntegerField()),
                ('travelHours', models.IntegerField()),
                ('trips', models.IntegerField()),
                ('winBidOrder', models.CharField(max_length=8)),
                ('techsRequired', models.BooleanField()),
                ('spcToolsRequired', models.BooleanField()),
                ('status', models.CharField(max_length=4)),
                ('statusDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractlocation')),
                ('billingNumber', models.DecimalField(decimal_places=0, max_digits=3)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('companyName', models.CharField(max_length=256)),
            ],
            bases=('api.abstractlocation',),
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractlocation')),
                ('name', models.CharField(max_length=128)),
                ('region', api.models.fields.Fields.RegionField(max_length=2)),
                ('manager', api.models.fields.Fields.TerritoryManagerField(max_length=2)),
            ],
            bases=('api.abstractlocation',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalOrder', models.CharField(max_length=8)),
                ('originalItem', models.DecimalField(decimal_places=0, max_digits=3)),
                ('originalDesc', models.CharField(max_length=30)),
                ('serviceCode', models.CharField(max_length=2)),
                ('warrantyCode', models.CharField(max_length=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderheader')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentType', models.CharField(max_length=2)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=2048)),
                ('lastUpdateBy', models.ForeignKey(on_delete=models.SET(api.helper.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('serviceOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderheader')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier', models.CharField(default='0', max_length=1)),
                ('type', models.CharField(default='0', max_length=1)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(default='', max_length=128)),
                ('workDays', models.SmallIntegerField(default=124)),
                ('active', models.BooleanField(default=True)),
                ('primaryCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledDate', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('travelHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrivalTime', models.DecimalField(decimal_places=0, max_digits=4)),
                ('onSiteHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('returnHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunchTime', models.DecimalField(decimal_places=0, max_digits=4)),
                ('confirmedBy', models.ForeignKey(on_delete=models.SET(api.helper.get_sentinel_user), related_name='confirmedBy', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderheader')),
                ('scheduledBy', models.ForeignKey(on_delete=models.SET(api.helper.get_sentinel_user), related_name='scheduledBy', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=models.SET(api.helper.get_sentinel_tech), to='api.technician')),
                ('serviceCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', api.models.fields.Fields.RegionField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serviceCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecenter')),
            ],
        ),
        migrations.AddField(
            model_name='orderheader',
            name='serviceCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecenter'),
        ),
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractlocation')),
                ('region', api.models.fields.Fields.RegionField(max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            bases=('api.abstractlocation',),
        ),
    ]
