# Generated by Django 4.1 on 2022-11-02 17:21

import api.helper
import api.models.fields.Fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1024)),
                ('street2', models.CharField(blank=True, default='', max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zipCode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('country', models.CharField(default='us', max_length=2)),
                ('county', models.CharField(max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitute', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(editable=False)),
                ('description', models.CharField(max_length=128)),
                ('laborHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('travelHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trips', models.DecimalField(decimal_places=0, max_digits=2)),
                ('status', api.models.fields.Fields.StatusCodeField(default='0', max_length=1)),
                ('statusDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(editable=False)),
                ('region', api.models.fields.Fields.RegionField(editable=False, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wedesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractlocation')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('companyName', models.CharField(blank=True, max_length=256, null=True)),
            ],
            bases=('api.abstractlocation',),
        ),
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractlocation')),
                ('region', api.models.fields.Fields.RegionField(max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            bases=('api.abstractlocation',),
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractlocation')),
                ('name', models.CharField(max_length=128)),
                ('region', api.models.fields.Fields.RegionField(max_length=2)),
                ('manager', api.models.fields.Fields.TerritoryManagerField(max_length=2)),
            ],
            bases=('api.abstractlocation',),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier', models.CharField(default='0', max_length=1)),
                ('type', models.CharField(default='0', max_length=1)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('workWeek', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workweek')),
                ('primaryCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecenter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(editable=False)),
                ('partOrder', models.CharField(max_length=8)),
                ('partItem', models.DecimalField(decimal_places=0, max_digits=3)),
                ('partDesc', models.CharField(max_length=30)),
                ('serviceCode', api.models.fields.Fields.ServiceCodeField(max_length=2)),
                ('warrantyCode', api.models.fields.Fields.WarrantyCodeField(max_length=1)),
                ('addendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='api.orderaddendum')),
            ],
        ),
        migrations.AddField(
            model_name='orderaddendum',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addendum_set', to='api.ordersequence'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentType', api.models.fields.Fields.CommentTypeField(max_length=1)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=2048)),
                ('lastUpdateBy', models.ForeignKey(on_delete=models.SET(api.helper.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderaddendum')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('startTime', models.TimeField(default=django.utils.timezone.now)),
                ('endTime', models.TimeField(default=django.utils.timezone.now)),
                ('travelHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confirmedBy', models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.helper.get_sentinel_user), related_name='confirmedBy', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_column='addendum_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='api.orderaddendum')),
                ('scheduledBy', models.ForeignKey(on_delete=models.SET(api.helper.get_sentinel_user), related_name='scheduledBy', to=settings.AUTH_USER_MODEL)),
                ('technicians', models.ManyToManyField(to='api.technician')),
                ('serviceCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', api.models.fields.Fields.RegionField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serviceCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecenter')),
            ],
        ),
        migrations.AddField(
            model_name='ordersequence',
            name='billingCust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AddField(
            model_name='ordersequence',
            name='jobSite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.jobsite'),
        ),
        migrations.AddField(
            model_name='ordersequence',
            name='serviceCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecenter'),
        ),
    ]
