# Generated by Django 4.1 on 2022-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractlocation',
            name='longitute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractlocation',
            name='street2',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
