# Generated by Django 4.1 on 2022-11-21 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 29, 47, 69946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 29, 47, 69926, tzinfo=datetime.timezone.utc)),
        ),
    ]
