# Generated by Django 4.1 on 2022-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orderitem_servicecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='excludeTax',
        ),
        migrations.RemoveField(
            model_name='orderheader',
            name='gateCode',
        ),
        migrations.RemoveField(
            model_name='orderheader',
            name='openSite',
        ),
        migrations.RemoveField(
            model_name='orderheader',
            name='poNumber',
        ),
        migrations.RemoveField(
            model_name='orderheader',
            name='spcToolsRequired',
        ),
        migrations.RemoveField(
            model_name='orderheader',
            name='winBidOrder',
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='statusDate',
            field=models.DateField(auto_now=True),
        ),
    ]
