# Generated by Django 4.1 on 2022-11-21 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_schedule_date_remove_schedule_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 54, 58, 159322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 54, 58, 159303, tzinfo=datetime.timezone.utc)),
        ),
    ]
