# Generated by Django 4.1 on 2022-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_orderheader_excludetax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='laborHours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='travelHours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='trips',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
