# Generated by Django 4.1 on 2022-11-21 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_schedule_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='confirmedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 20, 6, 58, 323634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduledBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduledBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 6, 58, 323616, tzinfo=datetime.timezone.utc)),
        ),
    ]
