# Generated by Django 4.1 on 2022-11-21 19:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_schedule_confirmedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 20, 48, 34, 671689, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
