# Generated by Django 4.1 on 2022-11-21 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_schedule_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 20, 48, 56, 287882, tzinfo=datetime.timezone.utc)),
        ),
    ]
