# Generated by Django 4.1 on 2022-11-21 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_schedule_enddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 20, 49, 19, 498701, tzinfo=datetime.timezone.utc)),
        ),
    ]
