# Generated by Django 4.1 on 2022-11-21 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_schedule_enddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='endDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='schedule',
            name='startDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(default=datetime.datetime.today),
        ),
    ]
