# Generated by Django 4.1 on 2022-11-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_schedule_enddate_schedule_endtime_schedule_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='startDateTime',
        ),
    ]
