# Generated by Django 4.1 on 2022-11-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_schedule_enddatetime_schedule_startdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
