# Generated by Django 4.1 on 2022-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_schedule_enddate_remove_schedule_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrenceRule',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
