# Generated by Django 4.1 on 2022-11-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_schedule_allday_schedule_recurrencerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='workWeek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workweek'),
        ),
    ]
