# Generated by Django 4.1 on 2022-12-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region'),
        ),
    ]
