# Generated by Django 4.1 on 2022-12-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
