# Generated by Django 4.1 on 2022-12-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_ordersequence_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='recurrenceRule',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
