# Generated by Django 4.1 on 2022-12-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecenter',
            name='manager',
        ),
    ]
