# Generated by Django 4.1 on 2022-12-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_servicecenter_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersequence',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manager'),
        ),
    ]
