# Generated by Django 4.1 on 2022-12-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_ordersequence_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='primaryCenter',
        ),
    ]
