# Generated by Django 4.1 on 2022-12-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_technician_primarycenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='centers',
            field=models.ManyToManyField(to='api.servicecenter'),
        ),
    ]
