# Generated by Django 4.1 on 2022-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_technician_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='region',
            field=models.ManyToManyField(to='api.region'),
        ),
    ]
