# Generated by Django 4.1 on 2022-12-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_ordersequence_unique_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersequence',
            name='region',
        ),
    ]
