# Generated by Django 4.1 on 2022-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_city_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='region',
            field=models.ManyToManyField(related_name='managers', to='api.region'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='technicians',
            field=models.ManyToManyField(related_name='schedules', to='api.technician'),
        ),
    ]
