# Generated by Django 4.1 on 2022-12-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_servicecenter_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='region',
        ),
    ]
