# Generated by Django 4.1 on 2022-12-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_zipcode_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipCodes', to='api.region'),
        ),
    ]
