# Generated by Django 4.1 on 2022-12-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_zipcode_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='city',
            new_name='cities',
        ),
    ]
