# Generated by Django 4.1 on 2022-12-29 16:30

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_city_zipcode_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='us', max_length=2),
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
            preserve_default=False,
        ),
    ]
