# Generated by Django 4.1 on 2022-12-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_city_country_city_county_city_state'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'state', 'country'), name='unique_city'),
        ),
    ]
