# Generated by Django 4.1 on 2023-01-09 19:40

import api.models.fields.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_city_unique_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=api.models.fields.Fields.AppointmentTypeField(default=1),
        ),
    ]
