# Generated by Django 4.1 on 2023-01-10 17:38

import api.models.fields.Fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=api.models.fields.Fields.AppointmentTypeField(default='ORDR', max_length=4),
        ),
    ]
