# Generated by Django 4.1 on 2023-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='returnHours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(),
        ),
    ]
