# Generated by Django 4.1 on 2023-01-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='returnHours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travelHours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
