# Generated by Django 4.1 on 2023-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_schedule_returnhours_alter_schedule_travelhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='returnHours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travelHours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
