# Generated by Django 4.1 on 2023-01-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_schedule_returnhours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(),
        ),
    ]
