# Generated by Django 4.1 on 2023-02-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_schedule_enddatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractlocation',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
