# Generated by Django 4.1 on 2023-02-10 00:26

import api.models.fields.Fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rename_longitute_abstractlocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=api.models.fields.Fields.AppointmentTypeField(max_length=4),
        ),
    ]
