# Production Stack

version: '3'
networks:
  prod-service-calendar:
    external: true

volumes:
  static:
  
services:
  gunicorn:
    build:
      context: ../
      dockerfile: ./prod/Dockerfile
    volumes:
      - static:/static
      - ./prod-settings.py:/usr/src/app/web/settings.py
    ports:
      - "8083:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - prod-service-calendar
    
  nginx:
    image: nginx:alpine
    volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/static
    ports:
      - "8082:80"
    depends_on:
      - gunicorn
    networks:
      - prod-service-calendar

  db:
    image: mariadb
    user: mysql:mysql
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - prod-service-calendar