# Production Stack

version: '3'
networks:
  prod-service-calendar:
    external: true

volumes:
  static:

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: ./prod/Dockerfile
    depends_on:
      - db
    networks:
      - prod-service-calendar
    
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8082:80"
    depends_on:
      - django_gunicorn

  db:
    image: mariadb
    user: mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - prod-service-calendar